# Generated by Django 3.0.7 on 2020-06-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('alt_titles', models.CharField(max_length=255)),
                ('lyrics', models.TextField()),
                ('notes', models.CharField(max_length=255)),
                ('date_created', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='compositions')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
            },
        ),
        migrations.CreateModel(
            name='PRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'pro',
                'verbose_name_plural': 'pros',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('publishing_notes', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='writers')),
            ],
            options={
                'verbose_name': 'writer ',
                'verbose_name_plural': 'writers',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('recording_type', models.CharField(max_length=50)),
                ('date_recorded', models.DateField()),
                ('is_mixed', models.BooleanField()),
                ('is_mastered', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='recordings')),
            ],
            options={
                'verbose_name': 'recording',
                'verbose_name_plural': 'recordings',
            },
        ),
        migrations.CreateModel(
            name='PublishingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admin', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_acct_num', models.IntegerField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.PRO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='publishingcompanies')),
            ],
            options={
                'verbose_name': 'publishingcompany',
                'verbose_name_plural': 'publishingcompanies',
            },
        ),
        migrations.CreateModel(
            name='CompositionWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.Composition')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.Writer')),
            ],
            options={
                'verbose_name': 'compositionwriter',
                'verbose_name_plural': 'compositionwriters',
            },
        ),
        migrations.CreateModel(
            name='CompositionRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('ownership_split', models.CharField(max_length=255)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.Composition')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.Recording')),
            ],
            options={
                'verbose_name': 'compositionrecording',
                'verbose_name_plural': 'compositionrecordings',
            },
        ),
        migrations.CreateModel(
            name='CompositionPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pro_work_num', models.IntegerField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.Composition')),
                ('publishing_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwrytrapp.PublishingCompany')),
            ],
            options={
                'verbose_name': 'compositionpublishing',
                'verbose_name_plural': 'compositionpublishings',
            },
        ),
    ]
