# Generated by Django 3.0.7 on 2020-06-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songwrytrapp', '0002_auto_20200616_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='pro_acct_num',
            new_name='pro_ipi',
        ),
    ]
