# Generated by Django 3.0.7 on 2020-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwrytrapp', '0006_auto_20200618_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='is_delivered',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recording',
            name='is_mastered',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recording',
            name='is_mixed',
            field=models.NullBooleanField(default=False),
        ),
    ]
